language: scala
scala:
   - 2.12.7
   
env:
  global:
    - CODECOV_TOKEN="2012b75d-83d9-4761-b782-6218f2aab7cd"

script:
   - sbt clean coverage test coverageReport
   
after_success:
  - bash <(curl -s https://codecov.io/bash) -t token
